name: Deploy Node Application

on:
    push:
        branches:
         - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t hurryep/demo_1 .
            - name: Publish Image to docker hub
              run: docker push hurryep/demo_1:latest 
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: pull image from docker hub
          run: docker pull hurryep/demo_1:latest
        - name: Delete old container
          run: docker rm -f node-app-container  
        - name: Run Docker Container
          run: docker run -d -p 8000:8000 --name node-app-container hurryep/demo_1:latest



